### ISSUE TITLE
preselected morphology comes up in expanded mode by default

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#574]
From Vanessa: something is odd about the way the morphologies are coming up: in expanded mode, as it were, with the “create new – report error – remove form” window open for the checked form.  Is this intentional?  From my point of view, it means an extra click for most words to close it, so I can see what other morphological choices are being offered (which are extending off the bottom of the page)

Introduced somewhere between commits
8500b3a
and
09641da

(or possibly between 09641da and af38308)

**Comment by LFDM** [comment]
Cannot confirm, neither on master nor on the deploy_jan5 branch.

`Expand selection` is a setting of the `morph` plugin which is **not** configurable - this means it is also not tracked by `userPreferences` and persisted in localStorage. It is however *sticky*, which means that if someone clicks expand selection manually and moves to a new chunk - things would still be expanded.

(probably makes sense to make this also a configurable setting though)

**Comment by balmas** [comment]
I'm guessing the sticky behavior might be what Vanessa was seeing then.  I agree it should be configurable and it might actually make sense for unsticky to be the default here.

**Comment by LFDM** [comment]
Just for clarification: Configurable means that one would be able to pre-define its value in a configuration file and that localStorage would be checked for it.

This would also mean, that it's immediately very sticky in fact.

I'd generally object about making it non-sticky. I think it makes more sense if it's sticky: If I want to expand selections and do it through the settings panel of the `morph` plugin, I will most likely want this to be present in the next chunk as well. 

Hm - stream of consciousness. The other use case would be that I just want to look at the tokens of a single chunk expanded - but actually don't care if the next sentence is also expanded. 

But still - I think if a user decides to look at this expanded, he has a reason to - and this reason might span across chunks. If the user would be interested in just a single expansion he could always just click the accordion item to open it up as a one off.

**Comment by balmas** [comment]
I'm recommending closing this because I think this was mostly due to confusion related to #593
