### ISSUE TITLE
arrows next to the sentence number at the top of the page are no longer higlighted

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#576]
Reported by Vanessa: Very minor detail, but the arrows next to the sentence number at the top of the page are no longer lighting up unless your cursor is actively on them.

 Introduced somewhere between commits
8500b3a
and
09641da

(or possibly between 09641da and af38308)

**Comment by LFDM** [comment]
Can anyone confirm this? The tone of the color is not ideal and not very different than the unhighlighted color, true (should be made more distinct), but there is still a difference (which means that the functionality itself is working fine)

**Comment by balmas** [comment]
as you say, I think the coloring of the available but not highlighted state could be better, but it is different from available state, and highlighted is highlighted when it should be.
