### ISSUE TITLE
If you select a group of tokens you can't easily deselect just the first one selected

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#598]
Noted by Vanessa:

If you click on a group of tokens, and then decide one in the group doesn’t belong, you can repeat the control+click in order to unselect that one item.  However, if that item that you want to unselect happens to be the first one selected, and you didn’t use control when you selected it, you cannot unselect it. 

This is possibly a long standing issue, and not super critical.

**Comment by LFDM** [comment]
Very interesting, never thought about that - but yes, that makes sense and is indeed a bug from the very first days...

**Comment by LFDM** [comment]
That's a pretty cool solution to this problem imo ;)
