### ISSUE TITLE
ui.indeterminate used?

### ISSUE THREAD

**Issue by LFDM** [latin-language-toolkit/arethusa#602]
@Christof, I remember you using it, but I don't think we do anymore?

@balmas, is this the reason why you added ui-utils to bower?

If but questions are answered with yes, we can remove this dependency again :)

**Comment by balmas** [comment]
I added it to bower because the build task failed without it .

**Comment by LFDM** [comment]
Hm interesting. This is something bower is really bad at - handling obsolete dependencies. This might just have been a remnant of and older bower install - we'll, I'll leave this open and investigate another time - not really important.

**Comment by balmas** [comment]
FWIW, the reference to ui.indeterminate remains in arethusa.core which is probably why the build failed. I'm not sure though if it needs to be there or not .. it could have been my mistake with a merge.  I see that Christof added it in this commit ee0e3be8ef75825bab7fdc7109d9e1bf19a05b26 and I don't see it removed after but it also shows as being added (back?) in my merge commit 956fc1bf49103873127b0e590e2956392160adcf

**Comment by Christof** [comment]
Sorry, I added and used it at some point for the token selection stuff. But in a redesign I deleted the parts where I used it. I will clean it up.
