### ISSUE TITLE
keyboard magnification

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#642]
Vanessa notes that students have trouble seeing accents and other chars on the Greek input keyboard. Would be nice to have a magnification option of some sort.

**Comment by Masoumeh** [comment]
It depends on the requirements of users.
We can just do it by adding the font styles (like front-size or font-weight) to the keyboard hover event in .css file (see the latest commit). On the other hand,  if more fancy features like zoom or magnifications are needed for each key, we should spend more time and use available libraries. As I have checked, most of them are designed for images and adding zoom feature to DOM elements needs special libraries. What do you think?

**Comment by balmas** [comment]
Fixed in f96452c
