### ISSUE TITLE
Update order of relation labels

### ISSUE THREAD

**Issue by LFDM** [latin-language-toolkit/arethusa#646]
`Aux` and `COORD` are too far down the chain.

**Comment by LFDM** [comment]
Closed by https://github.com/latin-language-toolkit/arethusa-configs/commit/bf3720e15a8c98e65bc3d1721a1071fada2eac7e

**Comment by LFDM** [comment]
Check again - did this went wrong?

**Comment by balmas** [comment]
@LFDM maybe we are suffering from there being 2 relations.json? One in arethusa and one in arethusa-configs? I think the app uses the one in arethusa??
