### ISSUE TITLE
checkbox size fix doesn't work in Firefox?

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#660]
I think the fix in 965012f3bf49b7317361429e81fa7e84085ddd6c doesn't work in firefox

**Comment by Masoumeh** [comment]
Please see the commit https://github.com/Masoumeh/arethusa/commit/a00f260086c5a6213a98e6df16e0e4d51e3a9437.

**Comment by balmas** [comment]
Hi @Masoumeh yes please submit a pull request for this fix. Thanks!

**Comment by balmas** [comment]
Fixed in a00f260
