### ISSUE TITLE
error saving morphology using smyth3 tagset

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#662]
Something in #640 or #641 (i.e as found in the deploy_20150330 branch) is causing an error in arethusa.morph updateGloss - form and selectedForm(id) are both returning undefined causing this to error out. I'm guessing something has changed in the timing as to when updateGloss is called.

**Comment by LFDM** [comment]
378a81d3ef26244a8d71ad111de71ba105003a77 reverted the commit which caused this - took a different approach to solve what i was trying to do (originally this issue: #633) in 787c068f15d0b133c913e636b61fabd8f6886267. All should be good again

**Comment by balmas** [comment]
adding comments from chat explaining the change:

this comes from a minor design flaw that's soon going to be fixed:
the unused token highlighter uses (through the stateChangeWatcher) the state.change api
or actually the state.watch api
which is notified everytime someone makes a state.change
the uTH declares which property it is interested in
for example relation.label
it would listen to a state.change('relation.label') change then
the problem is that morphology is calling state.change('morphology') changes
the property to listen to is therefore 'morphology'
but as on startup a morphology object is set, (with an empty lemma and an empty postag)
the initial count of unused tokens would be wrong
because a check if a 'morphology' object exists would return true
with the auxiliary property i define that the stateChangeWatch should actually check if the check-property is defined ('morphology') but also the auxiliary (in this case morphology.postag)
only then a token counts as used
 the original problem is that morphology can have three states
undefined
{ postag: '', lemma" '' }
and something which is really a valid form
my original change (which broke things) tried to change this
so that morphology is either set or not set
but apparently the gloss has some kind of dependency that something is there
and this would in fact have been the right change. doing what i did before and fix the dependency issue of this gloss
it would simplify the concepts involved
the underlying problem is feature creep:
the gloss thing was added on demand without a clear idea in mind
it doesn't really "fit" the way it's done

**Comment by balmas** [comment]
this appears to be fixed. Have deployed.
