### ISSUE TITLE
Cannot display properly

### ISSUE THREAD

**Issue by mzhai2** [latin-language-toolkit/arethusa#664]
Hi, arethusa looks really great and I would love to set it up but I'm running into issues displaying the pages correctly. The grunt server returns no errors and I checked the browser that everything is loaded. Here is what it looks like.
![screen shot 2015-04-02 at 12 15 11 am](https://cloud.githubusercontent.com/assets/5619828/6957777/2ef7b748-d8cf-11e4-94ab-0f671cc145f6.png)
I'm guessing I have a configuration error but I can't find any apparent errors.

**Comment by balmas** [comment]
It looks like one or more of the css and/or javascript files are not being loaded in your browser. Can you view the developer's console (in Firefox it's accessible via Tools, Web Developer, Web Console; in Chrome via Tools, Developer Tools) and see what errors are reported there?

It seems most likely to me that the sass css isn't compiled properly  -- Ruby 2.x is required for this, I'm not sure if that's adequately documented in the Readme.

**Comment by mzhai2** [comment]
Ruby 2.0.0 is installed but I did need to change the relative paths to absolute paths to the sass files in app/css/_foundation.scss

On http://localhost:8081/app/#/example_tb_review?doc=11&gold=1 Firefox's web console gives:  
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead arethusa_packages.min.js:353:0
syntax error app:1:1
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.min.js:3:6860
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ arethusa_packages.min.js:352:0
"Error: k.current[a] is undefined
S@http://localhost:8081/dist/arethusa.min.js:15:24154
T@http://localhost:8081/dist/arethusa.min.js:15:24213
P@http://localhost:8081/dist/arethusa.min.js:15:23948
sa@http://localhost:8081/dist/arethusa.min.js:15:26236
ya/<@http://localhost:8081/dist/arethusa.min.js:15:27087
Yd/this.$get</h.prototype.$digest@http://localhost:8081/dist/arethusa_packages.min.js:113:452
Yd/this.$get</h.prototype.$evalAsync/<@http://localhost:8081/dist/arethusa_packages.min.js:116:230
e@http://localhost:8081/dist/arethusa_packages.min.js:42:438
se/h.defer/c<@http://localhost:8081/dist/arethusa_packages.min.js:46:120
" arethusa_packages.min.js:96:209

syntax error app:1:1
"state.setState is DEPRECATED. Use state.change() instead." arethusa.min.js:13:6686
```

**Comment by mzhai2** [comment]
The scripts didn't work because I had custom aliases in my bash profile
