### ISSUE TITLE
selecting -- as option in a new form results in _ in postag

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#673]
Reported by @gcelano

A student has found an error in how the positive/comparative/superlative feature is saved, in the sense that when --- is selected ,instead of having a dash - saved, an underscore _ is saved. This of course creates problems when I try to compare the annotations because the two characters are different.
This is kinda important, because otherwise I get ptoblems with evaluating their annotations. If you can change it as soon as you can, that would be great. Thanks.

**Comment by balmas** [comment]
not sure if this is a tagset problem or an arethusa problem, quite possibly the former.

**Comment by balmas** [comment]
@gcelano - I'm not sure but I think this is maybe a long standing problem with creating new forms, and it's not limited to superlatives.  I.e. if you create a new noun form, for example, and leave any of the options (case, number, etc.) as -- you get an _ saved in that place in the postag.

**Comment by Masoumeh** [comment]
It seems the problem comes from the underscore assigned to postag.
I've created a pull request.

**Comment by balmas** [comment]
@gcelano please see comments in #694
