### ISSUE TITLE
Adverbs in Latin are wrongly saved if a new form is added from an adjective

### ISSUE THREAD

**Issue by gcelano** [latin-language-toolkit/arethusa#681]
If I have multus, which is automatically analyzed as an adjective, singular, nominative, etc. and I try to create an adverb lemma from it, the system saves the properties of the new form keeping the old ones as well: since the adverb has no case, for example, you will find this piece of information in the resulting @postag

See the analysis of "multum" here:

http://www.perseids.org/tools/arethusa/app/#/perseids?chunk=164&doc=11725

**Comment by balmas** [comment]
@Masoumeh ask @gcelano to explain this further if necessary

**Comment by Masoumeh** [comment]
The postags with a default value don't get update totally if the new form has less attributes. Seems it can be solved by updating the postag with the current attribute before saving. @balmas  please take a look at https://github.com/Masoumeh/arethusa/commit/24ecbc82f4bd838da12e211097d4f356bf9d0fc1 and give your feedback?

**Comment by balmas** [comment]
Hmm. @Masoumeh Were you actually able to reproduce the original problem? I have not been able to. In looking at the code, it seems like possibly this bug could occur if the change trigger in morph_create_form.html which calls updatePostag never happens. In this case, I think there is probably at least no harm in this change, but I would want to move it to the cleanUpAttributes function, e.g. maybe right after the line that sets `scope.form.attributes = cleanAttrs`.

**Comment by Masoumeh** [comment]
@balmas  Yes. It seems update postag changes the part related to the current attribute. So, those who don't change at all, keep the old values. 
I changed the line (see https://github.com/Masoumeh/arethusa/commit/560175c60fa6f44e3469e8fc759df8fc39ed55b5).

**Comment by balmas** [comment]
Fixed in f96452c
