### ISSUE TITLE
question on organization of plugins created by arethusa-cli init

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#683]
Question from @Masoumeh when following instructions in https://github.com/latin-language-toolkit/arethusa/blob/master/docs/custom/ngdoc/plugin_guide/00_temp.ngdoc

First of all, based on the documention when the following command,

$ arethusa init namespace title

a sepratate folder in the project is created, called namespace.title, while the other plugins
have all their data under the app folder of Arethusa.
I could imagine that this is to keep the new plugins separate from the current ones.
Is this the reason or they have different nature?

**Comment by balmas** [comment]
@Masoumeh  - yes the idea behind the setup described in the plugin guide, and supported by the arethusa-cli tool, was to allow development of plugins to occur outside of the main arethusa code base, so that anybody could easily write their own plugin for use with Arethusa.

We haven't actually tested plugins written in this way in a deployment environment yet though, so you may uncover some issues with this as you go through the process. These would be good to know about.

Please close this item if I've answered your question.

**Comment by Masoumeh** [comment]
Thanks. I got my answer. But I can't close it. You can close it.
