### ISSUE TITLE
error running tests on new plugin created via arethusa-init

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#684]
Question from @Masoumeh

 I got the following error when I add a plugin based on this document until
the "grunt spec" command,

  ReferenceError: Can't find variable: angular

Since the new plugin is dependent on Arethusa and the reference of angular exists
already in Arethusa, the plugin should find it. I could not find the actual reason.
The followings are the complete message which I get,

WARN [watcher]: Pattern "/home/rostam/arethusa/perseids.translations/bower_components/arethusa/dist/arethusa_packages.min.js" does not match any file.
WARN [watcher]: Pattern "/home/rostam/arethusa/perseids.translations/bower_components/angular-mocks/angular-mocks.js" does not match any file.
WARN [watcher]: Pattern "/home/rostam/arethusa/perseids.translations/bower_components/arethusa/spec/helpers/**/*" does not match any file.
WARN [watcher]: Pattern "/home/rostam/arethusa/perseids.translations/bower_components/arethusa/dist/arethusa.min.js" does not match any file.
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket L3Rtpa63jj_RLxf7ifyJ with id 52026989
PhantomJS 1.9.8 (Linux) ERROR
  ReferenceError: Can't find variable: angular
  at /home/rostam/arethusa/perseids.translations/app/js/perseids.translations.js:9

**Comment by balmas** [comment]
@Masoumeh,

I think you might be better off skipping the attempt to use the arethusa-cli tool to setup a new plugin for now, and instead make a copy of one that already exists in the main arethusa app to use as your base.

I'm struggling to get the arethusa-cli tool to setup a functional plugin myself and I think this tool might need more work before it's really functional.  The goal of these tools was to make development easier but as they are not really being maintained along with the code right now, they are perhaps not as helpful as they should be.

Let me know if you need help figuring out how to start from an existing plugin.

I think the documentation in the plugin developers guide is still very useful from the perspective of helping you understand the components of a plugin, and hopefully it will help you figure out what you need to do.

**Comment by PonteIneptique** [comment]
It's an interesting bug, because when I created the OpenDataGraph plugin, I had none of that using arethusa init plugin etc.
Just a comment : the error trace given here is not "helpful", as it stands for minified files. Chrome error are a little better when it comes to Angular (maybe run the tests in chrome ?)

I am sorry, just trying to understand what's going on. If this is not helpful, tell me.

**Comment by Masoumeh** [comment]
This error message was produced by phantomJS. 
Also, when I run it chrome the same error is thrown.

**Comment by balmas** [comment]
Masoumeh do you get the same error when running tests through Grunt on the arethusa code itself?

Is this maybe the same synchronization error you had when running the tests previously?

**Comment by Masoumeh** [comment]
Yes, I just follow the instructions in this document. I get the error when I run the "Grunt spec" command after few changes inside the spec file of the newly created plugin (as described in the document). This is totally different form the synchronization error I had.

**Comment by balmas** [comment]
Does it occur when running the Grunt spec task on the main arethusa code base?  If not, I think it's time to abandon the arethusa-cli plugin creation process for now in favor of using a current plugin as a template in order not to get stuck on this point.

**Comment by Masoumeh** [comment]
No, it doesn't. The Grunt spec task works on the main arethusa code base without any error. The error just appears when I run the Grunt spec task on the new plugin.
And I've just have started to follow the comment plugin in order to add a new plugin.

**Comment by balmas** [comment]
Ok, I've submitted this as a bug on arethusa-cli in https://github.com/latin-language-toolkit/arethusa-cli/issues/16 and am closing this question on the arethusa code then. Thanks!
