### ISSUE TITLE
If request for comments initially fails, display doesn't refresh as new comments are saved

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#686]
You can see this in the local server implementation as discussed at #685.

If the request for a comments document upon initialization of the application fails, saving comments can still succeed, but the display won't refresh.

**Comment by Masoumeh** [comment]
It seems it is corrected (see commit https://github.com/Masoumeh/arethusa/commit/82d7b2a800bbcc0a27f69c3f748aa335875613ca).

**Comment by balmas** [comment]
Hi @Masoumeh yes this looks fine - can you submit a pull request for this fix?

**Comment by balmas** [comment]
fixed in 82d7b2a
