### ISSUE TITLE
How to add a plugin into the visible tabs?

### ISSUE THREAD

**Issue by Masoumeh** [latin-language-toolkit/arethusa#690]
Where can I add a new plugin to the list of visible tabs?
(like comments, relation, morph, ....)
I have already added this plugin to the config file "staging"
but still no effect.

You can find the source code here:
https://github.com/Masoumeh/arethusa
The new plugin is "arethusa.reference".

@balmas

**Comment by balmas** [comment]
I believe you also need to add it to arethusaModules in Gruntfile.js

https://github.com/latin-language-toolkit/arethusa/blob/master/Gruntfile.js#L21-L40

**Comment by Masoumeh** [comment]
I had done it before: https://github.com/Masoumeh/arethusa/blob/master/Gruntfile.js

My feeling is that there should be some way to activate it since
not all plugins are shown in tabs.

**Comment by balmas** [comment]
I'm not sure I understand. I see it in when I load your code.
![screenshot from 2015-05-14 14 19 28](https://cloud.githubusercontent.com/assets/644870/7638631/43e60682-fa44-11e4-8034-afa461969cdd.png)

**Comment by Masoumeh** [comment]
I always opened "Try it yourself!" which still does not have this new plugin.
However, I see my plugin when I open "Review":
http://127.0.0.1:8081/app/#/example_tb_review?doc=11&gold=1

Can you explain me a little bit the difference?

**Comment by balmas** [comment]
Ok, this is a question of routes.  

E.g. see 
https://github.com/latin-language-toolkit/arethusa/blob/master/app/js/arethusa.js#L34-L37

if the path doesn't match on of the named routes, on line 37 you'll see that the fallback is to assume the path contains the name of the conf file:

`$routeProvider.when('/:conf', MAIN_ROUTE);`

(see also https://docs.angularjs.org/api/ngRoute/provider/$routeProvider)

If you look at the definition of MAIN_ROUTE at https://github.com/latin-language-toolkit/arethusa/blob/master/app/js/arethusa.core/routes/main.js#L19

you'll see it calls confUrl to define the url for the configuration file that is loaded

and confUrl uses the matched params stored in :conf to define the name of the json file to load

https://github.com/latin-language-toolkit/arethusa/blob/master/app/js/arethusa.core/conf_url.js#L14

`return confPath + params.conf + '.json';`

So when you click on the 'Try it yourself!' link on the landing page, you should see that it links to this url:

`http://localhost:8081/app/#/example_tb_create?doc=clean`

Which has the conf part of the path as `example_tb_create`

If you had added the reference plugin to the example_tb_create.json conf file, you would have seen it loaded in this case.

Does that make sense?

**Comment by Masoumeh** [comment]
Yes. I got the point. Thanks.
