### ISSUE TITLE
Retriever/Persister problem in reference module

### ISSUE THREAD

**Issue by Masoumeh** [latin-language-toolkit/arethusa#693]
I've added a retriever/persister to the reference module.
However, it does not find the retriever in self.conf. 

I've generated the reference_retriever using following command:
arethusa generate retriever ....

Then, here are the important changes in other files:

in staging.js:
"reference" : {
        "retriever" : {
            "ReferenceRetriever" : {
               "resource" : "arethusaServerReference"
            }
        }
    }

in reference.js:
function configure() {
      configurator.getConfAndDelegate(self);
      retriever = configurator.getRetriever(**self.conf.retriever**); -> is undefined
      persister = retriever;
    };

Source code under:
https://github.com/Masoumeh/arethusa

Any suggestions would be great.

**Comment by balmas** [comment]
Hi @Masoumeh this is actually working for me when I load your code, via e.g. http://localhost:8081/app/#/staging?doc=1

The retriever and persister are defined, but they aren't yet configured with a resource.

**Comment by Masoumeh** [comment]
Hi @balmas, 
you are right. I made a mistake.
However, I should mention that I use another spec files for testing as
the link "http://localhost:8081/app/#/staging?doc=1" is not working for me. 
I think that is the case because I could not get the data by 
"grunt import task" which gives me the following error:
 -- *Warning: Task "task" not found. Use --force to continue.*

**Comment by Masoumeh** [comment]
sadfa

**Comment by balmas** [comment]
@Masoumeh sorry maybe the instructions for grunt import were misleading -- there should be no "task" just 

```grunt import```

Let me know if that works for you.

**Comment by Masoumeh** [comment]
It does not work neither.
Should I add my public key somewhere?

This is the error:

**Running "shell:cloneExampleRepo" (shell) task**
**Cloning into 'data/examples'...**
**Permission denied (publickey).**
**fatal: Could not read from remote repository.**

**Please make sure you have the correct access rights**
**and the repository exists.**
**Warning: Command failed: Cloning into 'data/examples'...**
**Permission denied (publickey).**
**fatal: Could not read from remote repository.**

**Please make sure you have the correct access rights**
**and the repository exists.**
 **Use --force to continue.**

**Aborted due to warnings.**

**Comment by balmas** [comment]
Yes you either need to configure your access to github via ssh keys (see https://help.github.com/articles/generating-ssh-keys/) or change the urls used by the grunt import task to the https urls (you can find the urls in the cloneExampleRepo and cloneAuxConfigs tasks in the Gruntfile.js -- just change git@github.com: to https://github.com/)

**Comment by Masoumeh** [comment]
Thank you very much. 
It worked. It also creates the treebank folder correctly.

I am working now to have the resource for the reference.
I added the following code to dev.json:

  "arethusaServerReference" : {
        "route" : "/examples/reference/:doc",
        "params" : [ "doc" ]
  },

Now, the question is how to create this folder 
and a corresponding data file under the examples.

**Comment by balmas** [comment]
Clone https://github.com/latin-language-toolkit/arethusa-example-data 

add a reference folder under data

add your sample file to it

send a pull request :)
